### PR TITLE
Redesign editor form (editor.xhtml)

### LINKED ISSUE #73: Redesign editor form (editor.xhtml)

### PR DESCRIPTION
**Pull request by plutonik-a**
Fixes #73

### CODE REVIEW

**Comment by plutonik-a** [comment]
Screenshots of the current status:  

bildschirmfoto 2017-05-26 um 17 52 28

bildschirmfoto 2017-05-26 um 17 53 47

@tuurma  Please have a look at the labels. In the first image you can see a label "Person", which is only a placeholder. I need to know the correct wording here, please.

I have completed restructuring the first subform in `editor.xhtml` and styled it along the way. 
Now, I will continue with restructuring the rest of the file accordingly. 
And perhaps also the other forms, that now the layout is nearly completed and can be applied everywhere on the site.

**Comment by plutonik-a** [comment]
## Entire Editor form in FF / OSX

lgpn-editor-form-in-firefox-macosx

## Detail in Chrome OSX
bildschirmfoto 2017-06-01 um 14 09 41

bildschirmfoto 2017-06-01 um 14 09 52

**Comment by plutonik-a** [comment]
### Improve Responsive Buttons
bildschirmfoto 2017-06-01 um 21 45 19

bildschirmfoto 2017-06-01 um 21 45 33

**Comment by tuurma** [comment]
thanks @plutonik-a for tons of good work. I've been testing this morning, we have few issues that need to be fixed before merging your redesign into master:

1. autocomplete boxes in dynamically added sections are not present at all (eg. relationships > search relative, secondary & primary sources > reference abbreviation, place > search place); there was already problem with them being properly styled and fully functional but now the field doesn't show at all
2. delete buttons only after last repeat make it impossible to delete any of the previous entries
3. add/delete buttons disappear altogether after deleting all entries from repeat section (eg in status), so no way to reinstate them
4. add/delete doesn't work at all for Roman names and seems that deleting a name entry deletes Roman name

Most of the above are probably easy to fix things with repeat scope/binding, so I will try to fix them right away and present to the customer to comment on general look and feel.

**Comment by tuurma** [comment]
I have fixed many of the issues above, but I'm clueless about 1. @plutonik-a do you have any idea? Similar type of input works okay in adding sections in Names/Nyms

**Comment by plutonik-a** [comment]
@tuurma 
> I have fixed many of the issues above, but I'm clueless about 1. @plutonik-a do you have any idea? 

I'm going to have a look into this plus fix layout for the added `nyms` button and delete the button next to `attested forms`.

> Similar type of input works okay in adding sections in Names/Nyms

Hm, not working for me, though. I'll have a look into this, too.

All in all, I experienced a strange behavior when restructuring the markup: 
In the meantime I reached a state when all of the buttons and selects where replicated just fine as I remember (checked that quite regularly), but in return I got a strange layout bug with overflowing replicant containers. 
During further adjustments, the current bug appeared, I think.  
So, I checked out earlier commits, but couldn't reproduce neither the layout bug, nor the working state....  
I will have to thoroughly check all earlier commits again, I suppose.

**Comment by plutonik-a** [comment]
@tuurma 
Problem with selects is finally solved!  
It was in fact searching for the needle in a haystack, but in the end quite obvious:   
All replicable selects need a call for `clearAndInitAutocompletes();` in the add button within the `<xf:insert>` node! Otherwise the whole jQuery/select2 replacement won't be triggered.

**Comment by tuurma** [comment]
Cool @plutonik-a, thank you very much!

I wanted to demonstrate a certain issue that I mentioned in the hipchat earlier - it is possible to delete repeatable sections and no way to add them again, therefore the 'add ...' buttons should be there even if no  entry for any given section exists in the current form instance.

I paste the extreme version of the form where Names section is reduced to the final bracket etc

image

**Comment by tuurma** [comment]
When section is repeated, on the other hand, there are many 'add buttons' and their behaviour may seem confusing, since entry is added after last preexisting entry of the section, not nearest to the button. It is not much problem for Profession but in case of Names/Nyms, the subsection added can be way below the visible part of the form

image

**Comment by plutonik-a** [comment]
@tuurma 

> in case of Names/Nyms, the subsection added can be way below the visible part of the form

Correct. I was trying to change that, but didn't succeed, because whatever I tried, the `attested form` wouldn't be rendered at all. The problem is a nesting of repeats here.
`attested form` is nested in `name` and should be moved on to the same level. 

bildschirmfoto 2017-06-06 um 22 23 27

`name` should be replicated just below its first entry, I think, like all others.

**Comment by tuurma** [comment]
I've fixed some minor binding hiccups and I think we are almost ready to deploy for LGPN to see, I will just need to merge into the master. Thanks @plutonik-a for a great job on this!

**Pull request merged**
